# Site settings
title: FHIR Lab
email: joernguy.suess@csiro.au
description: > # this means to ignore newlines until "baseurl:"
  FHIR Lab is an interoperability reference infrastructure (sandbox), co-developed by UPM SILab and CSIRO, Australia.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jekyll.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll
gitlab_username:  jgsuess-csiro

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
