# Site settings
title: FHIR Lab
email: silab.upm@up.edu.ph
description: > # this means to ignore newlines until "baseurl:"
  Join the Community of Practice.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fhirlab.net" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll
#gitlab_username:  jgsuess-csiro

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
